name: external requests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # download the autoinstall scripts
    - name: Download autoinstall scripts
      uses: actions/checkout@v2
      with:
        repository: 'progetto201/progetto201-autoinstall'
    
    # Install apache and PHP
    - name: Use autoinstall to install apache and PHP
      run: |
        ls -a
        chmod +x autoapachephp/autoapachephp.sh
        ./autoapachephp/autoapachephp.sh -apachephp
        sudo apachectl -V
    
    # Install MySQL
    - name: Use autoinstall to install mysql
      run: |
        chmod +x automysql/automysql.sh
        ./automysql/automysql.sh -mysql -mysqlforphp
        mysql -V

    # Install Python
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    # Download this repository
    - name: Download api scripts
      uses: actions/checkout@v2
    
    # Import DB and change mysql pwd
    - name: Config MySQL
      run: |
        ls -a
        sudo mysql < "db100_100.sql"
        ./automysql/automysql.sh -mysqlpass test
    
    # "Install" the api by putting it in the www folder 
    - name: Move api to the www folder
      run: |
        sudo cp -r "api/." /var/www/
        find /var/www

    # Execute python script for the tests
    - name: Execute Python Scripts
      run: |
        python tests/test.py