name: external requests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # download the repository
    - name: Download repository
      uses: actions/checkout@v2
      
    # Start and configure apache-php docker container
    - name: Start Apache-PHP docker container
      run: |
        echo -e "\n[APACHE-PHP] Start on port 80 (internal 80), name apache-php-api, put folder api in /var/www/html"
        docker run -d -p 80:80 --name apache-php-api -v "$PWD/api":/var/www/html php:7.2-apache
        echo -e "\n\n[APACHE-PHP] Create credentials file"
        docker exec -it apache-php-api /bin/bash -c 'cd /var/www;mkdir credentials;echo -e "DB_HOST=mysql-server\nDB_USER100=root\nDB_PASS100=test" > credentials/credentials.ini'

    # Start MySQL docker container
    - name: Start MySQL docker container
      run: |
        echo -e "\n[MYSQL] Create folder for the volume"
        mkdir -p /storage/docker/mysql-datadir
        echo -e "\n\n[MYSQL] Start MySQL container, port 3306 (internal 3306), name mysql-server, volume, root password: test"
        docker run -d -p 3306:3306 --name mysql-server --volume=/storage/docker/mysql-datadir:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=test mysql:8.0.20
    
    # Set up the network between the containers
    - name: Set up share network
      run: |
        echo -e "\n[NETWORK] Create the network"
        docker network create sharedNet
        echo -e "\n\n[NETWORK] Connect apache-php container to the network"
        docker network connect sharedNet apache-php-api
        echo -e "\n\n[NETWORK] Connect mysql-server container to the network"
        docker network connect sharedNet mysql-server
        echo -e "\n\n[NETWORK] Try to ping between containers"
        docker exec -ti apache-php-api ping mysql-server

    # Install Python
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # Execute python test
    - name: Execute Python Test
      run: |
        python tests/test.py